data_params:
  random_state: 42
  test_size: 0.2
dataset:
  exclude_columns:
  - RID
  - VISCODE
  - MRI_acquired
  - research_group
  - subject_age
  metadata_path: D:\ADNI\AD_CN\proteomics\Biomarkers Consortium Plasma Proteomics
    MRM\metadata.csv
  name: mrm_small
model_params:
  dropout_rate: 0.1
  hidden_size: 8
original_config_path: configs/default.yml
timestamp: '2025-07-28T17:15:03.524082'
training_params:
  batch_size: 16
  learning_rate: 0.001
  num_epochs: 200
  patience: 20
  weight_decay: 1.0e-05
