data_params:
  random_state: 42
  test_size: 0.2
dataset:
  exclude_columns:
  - RID
  - VISCODE
  - research_group
  - subject_age
  metadata_path: D:\ADNI\AD_CN\proteomics\Biomarkers Consortium Plasma Proteomics
    MRM\proteomic_w_labels.csv
  name: proteomic_full
model_params:
  dropout_rate: 0.1
  hidden_size: 8
original_config_path: configs/default.yml
timestamp: '2025-08-07T21:46:08.541737'
training_params:
  batch_size: 16
  learning_rate: 0.001
  num_epochs: 200
  patience: 20
  weight_decay: 1.0e-05
