# TabNet experiment configuration for proteomic_full dataset
hidden_size: 8
dropout_rate: 0.1
num_epochs: 200
learning_rate: 0.001
patience: 20
batch_size: 16
weight_decay: 1.0e-5
test_size: 0.2
random_state: 42
base_path: "D:\\ADNI\\AD_CN\\proteomics\\Biomarkers Consortium Plasma Proteomics MRM"

# TabNet-specific parameters
tabnet_params:
  num_features: 8
  feature_dim: 64
  output_dim: 2
  num_decision_steps: 3
  relaxation_factor: 1.5
  sparsity_coefficient: 1.0e-5
  batch_momentum: 0.98
  virtual_batch_size: 128
  mask_type: "sparsemax"

# Dataset configurations
datasets:
  proteomic_full:
    name: proteomic_full
    metadata_path: "D:\\ADNI\\AD_CN\\proteomics\\Biomarkers Consortium Plasma Proteomics MRM\\proteomic_w_labels.csv"
    exclude_columns:
      - RID
      - VISCODE
      - research_group
      - subject_age 